export const TOWER_BUILD = 'TOWER_BUILD';
export const TOWER_STATE_CHANGE = 'TOWER_STATE_CHANGE';
export const GRID_SQUARE_BLOCK = 'GRID_SQUARE_BLOCK';

export const MONEY_ADD = 'MONEY_ADD'
export const MONEY_SPEND = 'MONEY_SPEND'
